# 配置数据库连接
spring:
  datasource:
    # 数据库连接URL，包括数据库地址、端口、数据库名称以及一些连接参数
    url: jdbc:mysql://localhost:3306/mybatis_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    # 数据源类型，这里使用的是HikariCP
    type: com.zaxxer.hikari.HikariDataSource
    # 数据库驱动类名，针对MySQL 8.0及以上版本
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库密码
    password: wxz123456
    # 数据库用户名
    username: root
    # HikariCP特定的配置
    hikari:
      # 最小空闲连接数
      minimum-idle: 5
      # 最大连接池大小
      maximum-pool-size: 9
      # 自动提交设置
      auto-commit: true
      # 连接池名称
      pool-name: MyHikariCP
      # 空闲连接的超时时间
      idle-timeout: 30000
      # 连接的最大生命周期
      max-lifetime: 1800000
      # 连接获取的超时时间
      connection-timeout: 30000
      # 用于检测连接是否有效的SQL查询
      connection-test-query: SELECT 1
